tired-of-cancer/eslint-config-toc

README.md, package.json, typescript.js
Our default config (airbnb) uses `import/prefer-default-export` to enforce a default (versus named) export when only one thing is exported from a module. I propose we invert this requirement and prefer (or require) named exports from all modules, regardless of how many exports they have.
The biggest advantage in my opinion is that we guarantee consistent component naming throughout the codebase, and allow our linters to warn us if we make a mistake. 
For a detailed bog on the benefits of inverting this rule, see: https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/
Since this configuration is only going to be used in future project, there is no impact yet.
If we would decide to add the config to the old Untire app project, we could add this snippet to its …
=> Prefer named export instead of default export

package.json
Fixes a missing file in the published NPM package. The prettier config file is used directly by our ESLint setup and needs to be included.
=> Add prettier rc config to published files index

README.md
Consumers of this library can ensure they use the same prettier configuration that we use in the ESLint ruleset by including it via their package json. This allows our library to remain the consistent source of truth when we update our prettier config.
=> Add documentation for including prettier config

README.md, package.json, tsconfig-react-native.json, tsconfig-react.json, tsconfig-typescript.json, tsconfig.json, yarn.lock
To further unify our linting we should also use the same TypeScript configuration where applicable. Using community recommendations will help prevent hard-to-debug typescript issues. See also: https://www.bayanbennett.com/posts/stop-messing-with-tsconfig/
Because TypeScript setup differs for vanilla TS, React and React Native projects, this configuration will need to offer one for each type of project.
Since this library is not in use in any real projects yet, there is no impact. These changes impact the installation steps and the README has been updated accordingly.
=> Add separate typescript templates for extension

.github/workflows/enforce-pr-labels.yml
Adds a workflow that will fail while the PR does not have at least one of the listed labels:
- bug
- documentation
- dependencies
- feature
This will help us ensure that the changelog in our release notes is correctly structured and the next semver version is correctly deduced from changes in recent PRs.
=> Add workflow to enforce pr labels

package.json, typescript.js, yarn.lock
I propose to keep our imports sorted alphabetically, at the top of the file, with a newline to separate blocks of imports from the rest of our code. This will make it easier to read the import section and file as a whole.
To have to do so manually might not be considered worth the effort, which is why I chose [eslint-plugin-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort) specifically: all of the configured rules can be auto-fixed by ESLint and Prettier. As long as we all use the same config (the whole idea of this project) it should be pretty seamless.
None, the package has not been applied to any project yet. Applying it to existing code bases will probably cause a lot of linting errors about imports, but those should be auto-fixable (`eslint . --fix`).
=> Add rules for sorting and placing imports

package.json, react-native.js, react.js, yarn.lock
Sorting the style properties in our style objects will make them more readable. Enforcing this manually might not be worth the trade-off but with this rule we can have our editor automatically fix the order for us.
None, the package has not been applied to any project yet. Applying it to existing code bases will probably cause a lot of linting errors about styling order, but those should be auto-fixable (`eslint . --fix`).
This PR also pins the dependency for `eslint-plugin-react-native` to v4 as a yarn package resolution. This is because otherwise `@react-native-community/eslint-config` explicitly installs version 3.x which is incompatible with eslint v8. See also: https://github.com/facebook/react-native/pull/31334
=> Propose sorting react native styles

react.js
I propose to keep our JSX props sorted alphabetically, with all callbacks sorted separately at the end. This will make it easier to read components and compare them.
To have to do so manually might not be considered worth the effort, but this rule can be auto-fixed by ESLint. As long as we all use the same config (the whole idea of this project) it should be pretty seamless.
None, the package has not been applied to any project yet. Applying it to existing code bases will probably cause a lot of linting errors about JSX property order, but those should be auto-fixable (`eslint . --fix`).
=> Add react jsx sort props rule

typescript.js
Traditionally, the maximum line length of code files has been 80 characters. However, with modern screens this is conservative. Even when comparing code side by side a line length of 100 or even 120 is often recommended. This proposal suggests to use 120.
None, the package has not been applied to any project yet. Applying it to existing code bases will probably cause a lot of linting errors about line wrapping, but those should be auto-fixable (eslint . --fix).
Changing the line length for ESLint will increase the chances of conflicting with Prettier's `print-width` rule, which also defaults to 80. This is often resolved by matching these rules (setting `print-width: 120` in this case). However, Prettier discourages this convention:
> For readability we recommend against using more than …
=> Set max line length to 120 ignoring long strings

typescript.js
Disallowing unused vars will help us clean up redundant properties and definitions.
None
=> Disallow unused vars

typescript.js
Disallowing the `any` type will help us increase TypeSafety from the get-go. Use `unknown` instead if necessary. See also https://dev.to/arikaturika/typescript-why-to-use-unknown-instead-of-any-41i8
Applying the package to existing code bases will probably cause a lot of linting errors about using the `any` type. These can be hard to fix because `any` is usually used as a last resort when applying a strong type is hard. As a halfway solution, replace all occurrences of `any` by `unknown`.
To downscale this error to a warning instead and solve those warnings gradually over time, add the following to your local `.eslintrc.json`:
```js
// Override no-explicit-any to give a warning instead of an error. 
// This gives us time to gradually refactor the type definitions. …
```
=> Disallow any as a type definition

typescript.js
To allow this configuration to apply to vanilla JS files as well (for example, these eslint configuration files themselves) we need to define a plugin and extension array for both general use, and for typescript specific rules (using the override option). I set this up with separate configuration using a shared `rules` object to prevent inconsistencies. However, updating the plugins and extensions still requires the developer to pay attention to not introduce inconsistencies between these configurations.
This PR adds separate config arrays for generic extensions/plugins and typescript-specific ones. These are then combined for the typescript override configuration. This means the developer now only needs to choose in which array to add the new plugin/extension, instead of making sure to …
=> Refactor typescript plugin extension definition

README.md
Apparently the resolution in package json for a known issue in the `eslint-plugin-react-native` dependency is not always passed on correctly to the project where this library is installed. The workaround seems to be to add the resolution to the project `package.json` as well. This is unfortunate, since it adds an extra instruction to the setup and will require a breaking change in the future when we no longer need the resolution, but the alternative is to downgrade the eslint dependency to v7 and that would also add complexity to the setup.
=> Add resolution note to documentation

.eslintrc.js, .prettierrc.js, README.md, nextjs.js, react-native.js, react.js, setup-plugins.js, typescript.js
By default, the airbnb config [enforces semicolons](https://github.com/airbnb/javascript#semicolons). Their reason for doing so is that when concatenated incorrectly, JavaScript files *could* be executed erroneously. This is such an edge-case however that many debates are held for and against the practice with the general consensus being that it doesn't really matter.
Usually I would be a proponent of sticking with the convention in such a case, but in this case I see a big advantage in omitting semicolons in our projects. When moving around lines of code (alt + up/down in VSCode), semicolons can get stuck in the wrong places. This usually leads to broken code. Easily fixable, but when it happens a lot it can slow you down.
In my opinion, the code becomes more readable and more easy to …
=> Disallow use of semicolon

typescript.js
We currently have conflicting rules when it comes to iterating over arrays programmatically. airbnb wants us to stay away from loops and use `forEach` and `map`. unicorn wants us to always use loops and refactor `forEach` into `for X in Y`. This means there currently is no valid way to iterate over arrays :sweat_smile:
After reading through a lengthy discussion on this, I think it is best to go with airbnb's side and disable the unicorn rule. Mainly because I think the actual details don't matter that much, but the airbnb guide is used often when working with React and React Native while the unicorn rules are less known and applied. By following airbnb we increase the chance that new developers on the project will have an easy time contributing.
Since we didn't encounter this issue …
=> Disable conflicting unicorn loop rule

.github/workflows/linting.yml
Apparently, without specifying, the linting action assumes that it should pass if any or all of the linters fail. 🤷 This PR specifies that we want the action to fail if any linter fails during the check 🤦
=> Fix linting workflow false negative

.gitignore, react.js, typescript.js
Moved [filename-case](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md) exception rule to typescript. So Typescript projects can also enjoy non-kebab-style-file-names 
None, Typescript projects will now benefit from this rule as well.
=> moved filename case to typescript

react.js, typescript.js
^ Add a GIF to cheer up the reviewers? Change the url to add your own.
Reverted filename-case rule since I merged it without a review and that's not the policy.
Untire-nxt-backend lint tests will fail. but I'll update those.
Add this snippet to a specific projects eslint config to (temporarily) ignore the proposed change.
```js
// Snippet
```
=> reverted filename case

README.md, package.json, tsconfig-nextjs.json, yarn.lock
Next.js projects need a different base config for their TypeScript setup than vanilla React projects. This PR proposes to add an extendable configuration file for those projects. It also unifies the setup steps in the documentation to keep a better overview.
Current projects using Next.js should update their tsconfig file as described in the updated README.
=> Add nextjs typescript base config file

tsconfig-react.json
As discussed in https://github.com/tired-of-cancer/untire-nxt-backend/pull/99#discussion_r1007286620; the tsconfig target for our react projects needed to be overridden to allow the use of certain (now standard) coding practices:
> The reason for this change is this warning:
> `Type 'Set<string>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher`
> When doing something like this:
> ```
>  const array = [1, 2, 3, 4, 1]
>  const arrayWithoutDuplicates = [...new Set(array)]
> ```
I propose that if this is the way of working we want, we should change the default config and not override the value at every individual project level. This config library extends the defaults from https://github.com/tsconfig/bases, and after some …
=> Proposal: Update react tsconfig target

react-native.js
When using a component called `<Link ... />` in React Native, the `jsx-a11y/anchor-is-valid` rule will complain if there is no valid `href` property set. The logic behind this is that screenreaders on the web will require this property on `<a />` tags to handle them correctly. However, since React Native works with Pressables instead of HTML tags this is no issue there.
There should be little to no impact. If this rule was ignored in specific cases the eslint-ignore statement may have to be removed to make CI pass.
=> Propose disable react native a11y link rule

renovate.json
We're getting a lot of simultaneous dependency updates, duplicated updates at different targets and most of them start rebasing as soon as one is merged. These changes in configuration should improve those issues and give us a more relaxed update routine.
none.
=> Propose better dependency schedule

package.json
Some of the recent dependency updates have caused a dependency resolution conflict for projects depending on this library. This can be solved by adding a resolution.
=> Fix eslint react plugin conflict

typescript.js
Function typing on array callbacks may get lost when not using them as a direct reference. See for example this issue on filtering undefined values from an array:
``` ts
const [breadOptions, setBreadOptions] = useState<Bread[]>([])
const breadResult = api?.products?.smallBreads || [] // (Bread | undefined)[]
const filteredBread = breadResult.filter((bread) => !!bread) // (Bread | undefined)[]
useEffect(() => {
setBreadOptions(filteredBread) // !! (Bread | undefined)[] is not assignable to Bread[]
}, [breadResult])
```
The values are filtered, but TypeScript does not pick up on it. This can be solved with a helper method like [suggested here](https://stackoverflow.com/questions/43118692/typescript-filter-out-nulls-from-an-array). However, when we follow this Unicorn rule the outcome will …
=> Propose disable unicorn no array callback reference

package.json, yarn.lock
The versions of `@typescript-eslint` included in the project directly and indirectly were conflicting, causing an error when trying to run `yarn install` with the current version.
We can safely remove the directly included library since it is included indirectly via the react, react-native and nodejs tooling.
Projects that upgraded to the current version will most likely have encountered this bug. Projects that did not can skip it. This bug fix should not have any negative impact.
=> Fix typescript eslint inconsistent dependency

package.json
In #95, tests were added and `yarn symlink` was added as the package.json `postinstall` script. This caused `yarn symlink` to be run when users of this package installed it as a dependency, causing it to fail in CI environments like `eas build`. 
This was never the intend and I thought `postinstall` was only run when running `yarn install` in this package directory itself. But that was not the case (never too old to learn). I've changed the scripts, so that the symlinks are only created when running `yarn test`, which should solve the problem.
- CI tests pass
=> Fix symlink creating when installing package

react.js
We often use `JSX.Element` and `ReactNode` interchangeable for the same purpose (specifying that a component can be passed along through the props of a component). The most common example is `{ children: JSX.Element }` versus `{ children: ReactNode }`.
Not only can this be confusing, but the global JSX namespace [has been deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464) as well. This PR proposes an additional React rule that will disallow the deprecated `JSX.Element` type in favour of the `ReactNode` type.
Typescript linting checks will fail on all usage of `JSX.Element` and suggest to replace it with `ReactNode`.
Add this snippet to a specific projects eslint config to (temporarily) ignore the proposed change.
```js
'@typescript-eslint/ban-types': [
'error',
{ …
```
=> Propose disallow jsx element type

package.json, react.js, tests/react/main.ts, tests/react/main.tsx, yarn.lock
Disables the `react/no-unescaped-entities` rule as it was interfering with the development process on the app. It caused single-quotes inside text components to be reported as errors, and it suggested to replace them by quote-codes. This is not what we want, as this does not play well with `translation.io`. This PR disabled them, allowing us to remove all the rule exemptions from the codebase.
- Added test-case
- Tests run in CI
=> Disable un-escaped-entities-rule
